### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by lukaszimmermann** [Barski-lab/cwl-airflow#1]
Installing cwl-airflow within an environment with Python 3 raises the following error:
ModuleNotFoundError: No module named 'ConfigParser'

This means cwl-airflow is not adapted to Python 3 currently. Is it planned to add Python 3 support in the future? Thanks!

**Comment by michael-kotliar** [comment]
Thanks for your comment @lukaszimmermann 
Currently cwl-airflow was tested only on Python 2.7. I'm planning to adopt it to Python 3 as soon as possible

**Comment by aunderwo** [comment]
Any news on updating to Python3. That would be awesome?
Are there plans for long term support of cwl-airflow?

**Comment by portah** [comment]
@aunderwo There is a 3.6 python package `pip3.6 install -U cwl-airflow-parser` it different from this code thou, you can find the new code https://github.com/datirium/cwl-airflow-parser

**Comment by michael-kotliar** [comment]
Updated to Python3
