### ISSUE TITLE
Update to Airflow 1.10.0 and latest cwltool

### ISSUE THREAD

**Issue by michael-kotliar** [Barski-lab/cwl-airflow#18]
Currently fails most of the conformance tests with Airflow 1.10.0

**Comment by canlar** [comment]
Hi,
if click create user in airflwo i get error.
Solution: update Flask-Admin

Test airflow 1.10:
i upgrade to airflow 1.10
airflow upgradedb is the one needed step to execute cwl in airflwo 1.10.

Do i need other steps ?
How i can use AWS Batch ?

Best regards
canlar

**Comment by canlar** [comment]
I edited airflow.cfg celery Parameter.
celeryd_concurrency >>> worker_concurrency
...

**Comment by michael-kotliar** [comment]
Hi @canlar,
Thank you for contributing to the development. Could you please provide more information about the system you are planning to build on AWS Batch?  Meanwhile, did you consider using [Google Cloud Composer](https://cloud.google.com/composer/)? It looks like they have already done part of the work towards running Airflow in cloud.
