### ISSUE TITLE
Job does not start right away if the system is not in UTC time.

### ISSUE THREAD

**Issue by shubham-padia** [Barski-lab/cwl-airflow#21]
The creation date of a job dag is set from the unix timestamp of the creation date of the corresponding job file.
`datetime.fromtimestamp()` converts the unix timestamp to local time, this may lead to a delay in running the dag if the system running airflow is not using UTC timezone.

**Comment by portah** [comment]
almost the same as #16

**Comment by portah** [comment]
@shubham-padia Thank you for the issue and PR, the issue almost the same as #16. @michael-kotliar will check the PR.
