### ISSUE TITLE
singularity support?

### ISSUE THREAD

**Issue by ionox0** [Barski-lab/cwl-airflow#25]
Just wondering if this tool happens to support singularity, perhaps by passing `cwltool --singularity` flag.

Thank you!

**Comment by michael-kotliar** [comment]
Hi @ionox0,
Thank you for your question. Most of our workflows are run in Docker, so I didn't have much time to work with Singularity. Theoretically we support Singularity as long as all other containers supported by cwltool. I will work on it soon and let you know.

**Comment by michael-kotliar** [comment]
Hi @ionox0 
You can set `singularity` flag in `airflow.cfg` file in the section `[cwl]` as follows
```
[cwl]
singularity = True
```
If this parameter is not set or `False`, Docker will be used.

To use this functionally, you should take the latest commit from `master` branch.

Let me know if you have any problems with this feature.
