### ISSUE TITLE
ImportError: No module named 'werkzeug.wrappers.json'

### ISSUE THREAD

**Issue by mr-c** [Barski-lab/cwl-airflow#28]
See the bottom of https://ci.commonwl.org/job/airflow-conformance/271/console

**Comment by michael-kotliar** [comment]
Thank you, I'll fix it. It's Flask related issue
`pip install Flask==1.0.4`

**Comment by mr-c** [comment]
Thanks, looks like https://github.com/Barski-lab/cwl-airflow/commit/7efdf76f78f3eb0b065788ea6cae355146c4234b fixed it
