### ISSUE TITLE
"cwl-airflow init" is gone?

### ISSUE THREAD

**Issue by mr-c** [Barski-lab/cwl-airflow#31]
```
+ cwl-airflow init -l 1 -p 1

usage: cwl-airflow [-h] {apiserver} ...
cwl-airflow: error: invalid choice: 'init' (choose from 'apiserver')
```

From the bottom of https://ci.commonwl.org/job/airflow-conformance/278/console

**Comment by michael-kotliar** [comment]
Thank you, I'm working on it. This is a new version of CWL-Airflow, so I haven't implemented the new mechanism of testing yet:)
