### ISSUE TITLE
CWLJobDispatcher Fails

### ISSUE THREAD

**Issue by manoskout** [Barski-lab/cwl-airflow#39]
**The execution stops on CWLJobDispatcher**
When I trigger the workflow for execution, it stops in the first step. As we can see in the logs below, the error is `KeyError`.

**To Reproduce**
1. Create the workflow 
1. Trigger the workflow 
2. Click on the update button in Airflow UI
3. The first step CWLJobDispatcher was failed

**Logs**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/cwl_airflow/extensions/operators/cwljobdispatcher.py", line 49, in execute
    job=context["dag_run"].conf["job"],
KeyError: 'job'
```
**Desktop :**
 - Docker
 - Python version (3.7)

**Comment by manoskout** [comment]
It was my mistake! I had a problem with my configuration JSON.

**Comment by dagrooms52** [comment]
I'm seeing the same issue. Can you please share which configuration file had a problem? 
This is a problem with cwl-airflow's error messaging, it's unclear where to look for the issue.

**Comment by dagrooms52** [comment]
This error doesn't come from CWL, Airflow, or the UI; the missing key comes from the DAG file. When triggering a job, pass a config JSON with the missing key as described in this [tutorial](https://cwl-airflow.readthedocs.io/en/latest/readme/how_to_use.html).

In this case, passing `{"job": "..."}` should work.
