### ISSUE TITLE
Support for managed Airflow via plugin

### ISSUE THREAD

**Issue by jeremyadamsfisher** [Barski-lab/cwl-airflow#60]
**Is your feature request related to a problem? Please describe.**
I would like to use a managed Airflow cluster like [MWAA](https://docs.aws.amazon.com/mwaa/latest/userguide/what-is-mwaa.html). Therefore, I cannot swap out the airflow executable. It can, however, take [custom plugins](https://docs.aws.amazon.com/mwaa/latest/userguide/configuring-dag-import-plugins.html).

**Describe the solution you'd like**
Distribute cwl-airflow as a plugin or the equivalent to work on a managed Airflow system

**Comment by michael-kotliar** [comment]
Hi @jeremyadamsfisher,

Thank you for your feature request. We are working on moving CWL-Airflow to the cloud, so smooth integration with MWAA is on our TODO list.

If you can install custom python packages on MWAA, you don't need to swap the original airflow executable. You just need to install CWL-Airflow package and create your DAGs using CWLDAG class. CWL-Airflow uses the original Airflow and only extends its functionality with the ability to parse and execute CWL workflows. Let me know if you need any questions about installation and configuration of CWL-Airflow.

**Comment by jeremyadamsfisher** [comment]
For others' reference, it seems one can install custom packages on MWAA: https://docs.aws.amazon.com/mwaa/latest/userguide/best-practices-dependencies.html
