### ISSUE TITLE
cwl-airflow api error 404 issue

### ISSUE THREAD

**Issue by kokleong9406** [Barski-lab/cwl-airflow#65]
First of all, thanks for writing this cwl-airflow! 

When I try to run "cwl-airflow api", the terminal got stuck at listening for very long:
![cwl-airflow-api](https://user-images.githubusercontent.com/37173629/126655858-213c8135-dd82-4360-8303-fb3ed2903207.png)

When I tried to access 127.0.0.1:8081 in my web browser, below is shown:
![127 0 0 1:8081](https://user-images.githubusercontent.com/37173629/126656520-d165bfed-3af8-488f-a1b7-5e06a77c6173.png)

I do not have any issue with "airflow webserver" though

I am currently using Ubuntu 18.04.5 LTS, Python 3.8.11
This is all my python packages version:
`Package                         Version
------------------------------- ------------------
alembic                         1.6.5
anyio                           3.2.1
apache-airflow                  2.0.0
apache-airflow-providers-ftp    1.1.0
apache-airflow-providers-http   1.1.1
apache-airflow-providers-imap   1.0.1
apache-airflow-providers-sqlite 1.0.2
apispec                         3.3.2
argcomplete                     1.12.3
attrs                           20.3.0
Babel                           2.9.1
bagit                           1.8.1
blinker                         1.4
CacheControl                    0.12.6
cached-property                 1.5.2
cattrs                          1.5.0
certifi                         2021.5.30
cffi                            1.14.6
chardet                         3.0.4
click                           7.1.2
clickclick                      20.10.2
colorama                        0.4.4
coloredlogs                     15.0.1
colorlog                        4.0.2
commonmark                      0.9.1
connexion                       2.9.0
croniter                        0.3.37
cryptography                    3.4.7
cwl-airflow                     1.2.10
cwltest                         2.0.20200626112502
cwltool                         3.0.20200710214758
decorator                       4.4.2
defusedxml                      0.7.1
dill                            0.3.4
dnspython                       2.1.0
docker                          5.0.0
docutils                        0.16
email-validator                 1.1.3
Flask                           1.1.4
Flask-AppBuilder                3.1.1
Flask-Babel                     1.0.0
Flask-Caching                   1.10.1
Flask-JWT-Extended              3.25.1
Flask-Login                     0.4.1
Flask-OpenID                    1.2.5
Flask-SQLAlchemy                2.5.1
flask-swagger                   0.2.13
Flask-WTF                       0.14.3
funcsigs                        1.0.2
graphviz                        0.17
greenlet                        1.1.0
gunicorn                        19.10.0
h11                             0.12.0
httpcore                        0.13.6
httpx                           0.18.2
humanfriendly                   9.2
idna                            2.10
importlib-metadata              1.7.0
importlib-resources             1.5.0
inflection                      0.5.1
iso8601                         0.1.16
isodate                         0.6.0
itsdangerous                    1.1.0
Jinja2                          2.11.3
json-merge-patch                0.2
jsonmerge                       1.8.0
jsonschema                      3.2.0
junit-xml                       1.9
lazy-object-proxy               1.4.3
lockfile                        0.12.2
lxml                            4.6.3
Mako                            1.1.4
Markdown                        3.3.4
MarkupSafe                      1.1.1
marshmallow                     3.13.0
marshmallow-enum                1.5.1
marshmallow-oneofschema         3.0.1
marshmallow-sqlalchemy          0.23.1
mistune                         0.8.4
msgpack                         1.0.2
mypy-extensions                 0.4.3
natsort                         7.1.1
networkx                        2.5.1
numpy                           1.21.1
openapi-schema-validator        0.1.5
openapi-spec-validator          0.3.1
pandas                          1.3.0
pendulum                        2.1.2
pip                             21.1.3
prison                          0.1.3
prov                            1.5.1
psutil                          5.8.0
pycparser                       2.20
Pygments                        2.9.0
PyJWT                           1.7.1
pyparsing                       2.4.7
pyrsistent                      0.18.0
python-daemon                   2.3.0
python-dateutil                 2.8.2
python-editor                   1.0.4
python-nvd3                     0.15.0
python-slugify                  4.0.1
python3-openid                  3.2.0
pytz                            2021.1
pytzdata                        2020.1
PyYAML                          5.4.1
rdflib                          4.2.2
rdflib-jsonld                   0.5.0
requests                        2.23.0
rfc3986                         1.5.0
rich                            9.2.0
ruamel.yaml                     0.16.5
schema-salad                    7.1.20210611090601
setproctitle                    1.2.2
setuptools                      57.4.0
shellescape                     3.4.1
six                             1.16.0
sniffio                         1.2.0
SQLAlchemy                      1.3.24
SQLAlchemy-JSONField            1.0.0
SQLAlchemy-Utils                0.37.8
swagger-ui-bundle               0.0.8
tabulate                        0.8.9
tenacity                        6.2.0
termcolor                       1.1.0
text-unidecode                  1.3
thrift                          0.13.0
tornado                         6.1
typing-extensions               3.10.0.0
tzlocal                         1.5.1
unicodecsv                      0.14.1
urllib3                         1.25.11
websocket-client                1.1.0
Werkzeug                        1.0.1
wheel                           0.36.2
WTForms                         2.3.3
zipp                            3.5.0
`

**Comment by michael-kotliar** [comment]
Hello @kokleong9406,
Thanks for using CWL-Airflow. Our API is not a web interface, so the URL you are trying to open won't work. Its main purpose is to allow other programs to connect to CWL-Airflow for submitting new pipelines and jobs. To get the list of available endpoints you can open http://localhost:8081/api/experimental/ui/ in your web browser after you started `cwl-airflow api`. Let me know if you have any other questions about CWL-Airflow API.
