### ISSUE TITLE
Change airflow dependency to less restrictive

### ISSUE THREAD

**Issue by agaszmurlo** [Barski-lab/cwl-airflow#69]
Currently cwl-airflow has specific version of Apache Airflow (==2.0.1) in install_requires section. It is generally not considered best practicie accoriding to Python Packaging User Guide:  https://packaging.python.org/discussions/install-requires-vs-requirements/

Please consider changing the requirements to less restrictive (>=2.0.1)

**Comment by michael-kotliar** [comment]
@agaszmurlo, thank you for the submitted issue,

I'm trying to stick to the specific Airflow releases as each Airflow version has constraints defined here
`https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt`
Using the latest Airflow versions often creates dependencies problems. I will update to the latest Airflow as soon as I test that everything works fine with that release.

Best regards,
Michael

**Comment by michael-kotliar** [comment]
Hi @agaszmurlo,
Please see the latest CWL-Airflow 1.2.11 with Apache Airflow 2.1.4.

Thanks for using CWL-Airflow

**Comment by michael-kotliar** [comment]
Feel free to reopen this issue if the problem still exists.
