### ISSUE TITLE
BashOperator + CWLDAG

### ISSUE THREAD

**Issue by kokleong9406** [Barski-lab/cwl-airflow#73]
Hi, I would like to ask does Airflow BashOperator work with CWLDAG? My job will fail, even though I am running a simple echo in BashOperator. Nevertheless, it works well if I am using PythonOperator. Let me know if you need the files to reproduce the errors. Allow me to share a snippet of my dag script:

![image](https://user-images.githubusercontent.com/37173629/134650823-2174f146-7779-4ec0-bc35-459ee8cad425.png)

Below is the DAG when viewed in Airflow Web UI:

![image](https://user-images.githubusercontent.com/37173629/134651113-51a278a7-7f9e-4193-91a2-ac2559f83fea.png)

**Comment by michael-kotliar** [comment]
Hello @kokleong9406 

Thanks for using CWL-Airflow. Could you please provide more details about what you are trying to achieve by adding extra steps to CWLDAG? From what I understand from the attached screenshot you just want to add a step that will download the required input files. To solve this problem, I would just create a custom `CWLJobDispatcher` class and use it in the CWLDAG constructor. From the link below you can see that you can provide your own versions for `dispatcher` and `gatherer` steps. 
https://github.com/Barski-lab/cwl-airflow/blob/63d8d234f2bcc56e8a2d5e6a9b10f72ecf80bf75/cwl_airflow/extensions/cwldag.py#L25
Let me know if you need any help with that.

Michael

**Comment by michael-kotliar** [comment]
Hi @kokleong9406,

Yeah, you are right, having everything inside CWL file is a more preferable approach. I will close this issue for now. Feel free to reopen it if you have any other questions.

Michael
